#!/usr/bin/env python3
"""Generate the C header that lets the DSP serve its own contract.

The chain host asks an audio FX for `chain_params` before falling back to
module.json -- and that fallback re-serialises the JSON with only a handful of
fields, dropping `viz`, `live`, `access` and `step`. Without them the gain
reduction meter loses its widget, its per-tick refresh and its read-only
frame. So the plugin serves the full JSON itself, and this script derives it
from src/module.json at build time so the two can never disagree.

    scripts/gen_contract.py src/module.json build/contract_gen.h
"""

import json
import sys


def c_literal(text, width=96):
    """Render `text` as a sequence of adjacent C string literals."""
    # One token per source character, so a line break can never land inside
    # an escape sequence.
    tokens = []
    for ch in text:
        if ch in '"\\':
            tokens.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            tokens.append(ch)
        else:
            # Octal escapes are bounded at three digits, so a following
            # character can never be swallowed the way a \x escape would.
            tokens.append("".join("\\%03o" % b for b in ch.encode("utf-8")))
    lines, cur = [], ""
    for tok in tokens:
        if cur and len(cur) + len(tok) > width:
            lines.append(cur)
            cur = ""
        cur += tok
    if cur:
        lines.append(cur)
    return "\n".join('    "' + ln + '"' for ln in lines) if lines else '    ""'


def main(argv):
    if len(argv) != 3:
        sys.stderr.write(__doc__)
        return 2
    with open(argv[1], encoding="utf-8") as f:
        module = json.load(f)
    caps = module.get("capabilities") or {}
    params = caps.get("chain_params")
    hierarchy = caps.get("ui_hierarchy")
    if not isinstance(params, list) or not params:
        sys.stderr.write("gen_contract: module.json has no capabilities.chain_params\n")
        return 1
    if not isinstance(hierarchy, dict) or "levels" not in hierarchy:
        sys.stderr.write("gen_contract: module.json has no capabilities.ui_hierarchy.levels\n")
        return 1

    compact = dict(separators=(",", ":"), ensure_ascii=False)
    params_json = json.dumps(params, **compact)
    hierarchy_json = json.dumps(hierarchy, **compact)

    with open(argv[2], "w", encoding="utf-8") as f:
        f.write("/* GENERATED by scripts/gen_contract.py from src/module.json -- do not edit. */\n")
        f.write("#ifndef COMP_CONTRACT_GEN_H\n#define COMP_CONTRACT_GEN_H\n\n")
        f.write("#define COMP_CHAIN_PARAMS_JSON \\\n" + c_literal(params_json).replace("\n", " \\\n") + "\n\n")
        f.write("#define COMP_UI_HIERARCHY_JSON \\\n" + c_literal(hierarchy_json).replace("\n", " \\\n") + "\n\n")
        f.write("#endif\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
